server:
    port: 3030
    servlet:
        context-path: /auth-server

spring:
    profiles:
        default: default
    security:
        user:
            name: Debuggeando
            password: ideas
            roles: VIEWER
    application:
        name: auth-server
    datasource:
        url: jdbc:postgresql://localhost:5432/authorized
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 10
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

# eureka:
#     instance:
#         instance-id: "${spring.application.name}:${server.port}"
#     client:
#         fetch-registry: true
#         service-url:
#             defaultZone: http://localhost:8761/eureka/

application:
    jwt:
        secret: 2a8b1c2d3e7f7g7h7i7j7k7l7m7n8o9p0q1r2s3t4u5v6
        expiration-in-ms: 30000
