server:
    port: 8080

spring:
    application:
        name: authorized-ms
    profiles:
        default: eureka-on
    datasource:
        url: jdbc:postgresql://localhost:5432/reactauthdb
        username: postgres
        password: postgres
        driver-class-name: org.postgresql.Driver
        hikari:
            connection-timeout: 30000
            maximum-pool-size: 10
    jpa:
        database: postgresql
        show-sql: false
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true

eureka:
    instance:
        instance-id: "${spring.application.name}:${server.port}"
    client:
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/