server:
    port: 8887

spring:
    application:
        name: gateway-server-ms
    profiles:
        default: eureka-on

eureka:
    client:
        fetch-registry: true
        service-url:
            defaultZone: http://localhost:8761/eureka/

management:
    endpoint:
        gateway:
            enabled: true
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: "*"

security:
    auth-server:
        url: "http://localhost:3030/auth-server/auth/validateTokenAuth"
        access-token-header: "accessToken"